server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
    location ~* \.pdf$ {
        sendfile off; 
        gzip off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~* \.(css|js|jpg|png|svg|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}